root: true

plugins:
    - "node"

extends:
    - "eslint"
    - "plugin:node/recommended"

rules:
    space-before-function-paren:
        - error
        - anonymous: always
          named: never
    no-use-before-define: off
    require-jsdoc: off
    no-var: error
    one-var:
        - error
        - never
    func-style:
        - error
        - declaration
        - allowArrowFunctions: true
